# Add Exponents to a Multi-Index Set

In [1]:
import minterpy as mp
import numpy as np

This guides shows how to add an exponent or a set of exponents may be added to a `MultiIndexSet` instance.

## Create a `MultiIndexSet` instance

Suppose we have a complete multi-index set for multivariate polynomials of dimension $4$, degree $2$, and $l_p$ degree $1.0$:

In [2]:
mi = mp.MultiIndexSet.from_degree(4, 2, 1)

In [3]:
print(mi)

MultiIndexSet
[[0 0 0 0]
 [1 0 0 0]
 [2 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 2]]


## Add an exponent to a `MultiIndexSet` instance

The method `add_exponents()` inserts an exponent to a `MultiIndexSet` instance. The exponents must be given as a NumPy integer array of the correct dimension.
Suppose now we'd like to add a new exponent element $\left( 0, 0, 3, 0 \right)$:

In [13]:
new_exp = np.array([[0, 0, 3, 0]], dtype=int)
new_exp

array([[0, 0, 3, 0]])

Notice that the array is of shape $1 \times 4$ because the dimension of the multi-index set is $4$ and one new element is to be added.
To add the exponent:

In [14]:
mi.add_exponents(new_exp)

MultiIndexSet
[[0 0 0 0]
 [1 0 0 0]
 [2 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 3 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 2]]

The new exponent is lexicographically added to the previous set of exponents. In the example above, the element $\left( 0, 0, 3, 0 \right)$ comes right after $\left( 0, 0, 2, 0 \right)$ and before $\left( 0, 0, 0, 1 \right)$.

The method `add_exponents()` returns a new instance of `MultiIndexSet` with extended exponents; the change does not happen in-place and should be stored in a different variable for later usage:

In [15]:
mi_ext = mi.add_exponents(new_exp)

In [16]:
print(mi_ext)

MultiIndexSet
[[0 0 0 0]
 [1 0 0 0]
 [2 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 3 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 2]]


Notice that the new instance has a higher polynomial degree than the original one:

In [30]:
mi_ext.poly_degree

3

This degree corresponds to the degree $p$ such that the condition $\lVert \boldsymbol{\alpha} \rVert_p = (\alpha_1^p + \alpha_2^p + \alpha_3^p + \alpha_4^p)^{\frac{1}{p}} \leq 1.0 = l_p$ for all $\boldsymbol{\alpha} \in A$ holds.

## Add a set of exponents to a `MultiIndexSet` instance

The method `add_exponents()` also supports multiple exponents. For instance, the following exponents can be added:

$$
B = \left\{ (3, 0, 0, 0), (0, 3, 0, 0), (0, 0, 0, 3) \right\}
$$

In [31]:
exps = np.array([
    [3, 0, 0, 0],
    [0, 3, 0, 0],
    [0, 0, 0, 3],
])

In [32]:
mi.add_exponents(exps)

MultiIndexSet
[[0 0 0 0]
 [1 0 0 0]
 [2 0 0 0]
 [3 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 2 0 0]
 [0 3 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [0 0 2 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 2]
 [0 0 0 3]]

As before the new exponents are added lexicographically to the existing set of exponents. As mentioned, the method returns a new instance and does not modify the current instance in place.