# Make a Multi-Index Set Complete

In [1]:
import minterpy as mp
import numpy as np

A multi-index set $A$ is said to be _complete_ if, for a given polynomial of degree $n \in \mathbb{N}$ under $l_p$-norm, it contains all the exponents such that $\lVert \boldsymbol{\alpha} \rVert_p = (\alpha_1^p + \ldots + \alpha_M^p)^{\frac{1}{p}} \leq n$ for all $\boldsymbol{\alpha} \in A$.

This guide shows how to check a given `MultiIndexSet` instance for completeness and make the corresponding set of exponents complete.

## Motivating example

Consider a (incomplete) three-dimensional multi-index set with a single element and $l_p$-degree of $2.0$ as follows:

$$
A = \{ (0, 0, 2) \}
$$

This multi-index set can be created in Minterpy as follows:

In [12]:
mi = mp.MultiIndexSet(np.array([[0, 0, 2]]), lp_degree=2.0)

In [13]:
print(mi)

MultiIndexSet
[[0 0 2]]


## Check for completeness

The property `is_complete` of a `MultiIndexSet` instance returns `True` if the set of exponents in the instance is complete and `False` otherwise. 

In [14]:
mi.is_complete

False

## Make complete

The method `make_complete()` creates a complete multi-index set from a given instance of `MultiIndexSet`.

In [15]:
mi.make_complete()

MultiIndexSet
[[0 0 0]
 [1 0 0]
 [2 0 0]
 [0 1 0]
 [1 1 0]
 [0 2 0]
 [0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [0 0 2]]

The method returns a new instance of `MultiIndexSet` and can be stored in a variable for further use:

In [16]:
mi_complete = mi.make_complete()

And indeed, the resulting multi-index set is complete:

In [10]:
mi_complete.is_complete

True